version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.AspNetCore.TestHost
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Microsoft.Extensions.Primitives
    versions:
    - 5.0.0
    - 5.0.1
  - dependency-name: Arbor.ModelBinding.NewtonsoftJson
    versions:
    - 1.1.0-build.1617222349.systemtextjson
    - 1.1.0-build.1617741586.systemtextjson
  - dependency-name: Arbor.ModelBinding
    versions:
    - 0.7.2
    - 1.0.0
    - 1.1.0-build.1617741586.systemtextjson
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
    - 16.9.4
  - dependency-name: Serilog.AspNetCore
    versions:
    - 3.4.0
    - 4.0.0
    - 4.1.0
  - dependency-name: Newtonsoft.Json
    versions:
    - 13.0.1
  - dependency-name: Machine.Specifications.Runner.VisualStudio
    versions:
    - 2.10.1
  - dependency-name: serilog.aspnetcore
    versions:
    - 3.4.0
  - dependency-name: Microsoft.Extensions.Logging.Abstractions
    versions:
    - 5.0.0
  - dependency-name: serilog
    versions:
    - 2.10.0
